export const components = {
  CaptionItem: () => import('./caption/Item.vue'),
  CaptionForm: () => import('./caption/Form.vue'),
  CaptionView: () => import('./caption/View.vue'),
  SeparatorItem: () => import('./separator/Item.vue'),
  SeparatorForm: () => import('./separator/Form.vue'),
  SeparatorView: () => import('./separator/View.vue'),
  NavigationItem: () => import('./navigation/Item.vue'),
  NavigationForm: () => import('./navigation/Form.vue'),
  NavigationView: () => import('./navigation/View.vue'),
  NoticeItem: () => import('./notice/Item.vue'),
  NoticeView: () => import('./notice/View.vue'),
  NoticeForm: () => import('./notice/Form.vue'),
  PictureadItem: () => import('./PictureadItem.vue'),
  PictureadView: () => import('./PictureadView.vue'),
  PictureadForm: () => import('./PictureadForm.vue'),
  VideoItem: () => import('./VideoItem.vue'),
  VideoView: () => import('./VideoView.vue'),
  VideoForm: () => import('./VideoForm.vue'),
  RichtextItem: () => import('./richtext/Item.vue'),
  RichtextView: () => import('./richtext/View.vue'),
  RichtextForm: () => import('./richtext/Form.vue'),
  GoodsListItem: () => import('./goods-list/Item.vue'),
  GoodsListView: () => import('./goods-list/View.vue'),
  GoodsListForm: () => import('./goods-list/Form.vue'),
  GoodsCategoryItem: () => import('./goods-category/Item.vue'),
  GoodsCategoryView: () => import('./goods-category/View.vue'),
  GoodsCategoryForm: () => import('./goods-category/Form.vue'),
  ShopItem: () => import('./shop/Item.vue'),
  ShopView: () => import('./shop/View.vue'),
  ShopForm: () => import('./shop/Form.vue'),
  CouponItem: () => import('./CouponItem.vue'),
  CouponForm: () => import('./CouponForm.vue'),
  CouponView: () => import('./CouponView.vue'),
  // todo 团购暂时可以不上
  // GroupBuyingItem: () => import('./GroupBuyingItem.vue'),
  // GroupBuyingForm: () => import('./GroupBuyingForm.vue'),
  // GroupBuyingView: () => import('./GroupBuyingView.vue'),
  CustomerServiceItem: () => import('./customer-service/Item.vue'),
  CustomerServiceForm: () => import('./customer-service/Form.vue'),
  CustomerServiceView: () => import('./customer-service/View.vue'),
  SearchItem: () => import('./search/Item.vue'),
  SearchForm: () => import('./search/Form.vue'),
  SearchView: () => import('./search/View.vue'),
  GroupBookingItem: () => import('./GroupBookingItem.vue'),
  GroupBookingForm: () => import('./GroupBookingForm.vue'),
  GroupBookingView: () => import('./GroupBookingView.vue'),
  InstantDeathItem: () => import('./InstantDeathItem.vue'),
  InstantDeathForm: () => import('./InstantDeathForm.vue'),
  InstantDeathView: () => import('./InstantDeathView.vue'),
}

const metaImports = [
  import('./caption/config'),
  import('./navigation/config'),
  import('./goods-list/config'),
  import('./goods-category/config'),
  import('./richtext/config'),
  import('./search/config'),
  import('./separator/config'),
  import('./video'),
  import('./notice/config'),
  import('./picturead'),
  import('./customer-service/config'),
  import('./shop/config'),

  import('./coupon'),
  // todo 团购暂时可以不上
  // import('./group-buying'),
  import('./group-booking'),
  import('./instant-death')
]

export async function getItemExportList() {
  const results = await Promise.all(metaImports)
  return results
}
